[summarization]
prompt = """
Below is the initial summary of our conversation. 
Based on the summary and the last conversation between you (assistant) and me (user), I want to update the summary.

**Initial Summary:** 
$previous_summary

**Last Conversation:**
$latest_conversation

When updating the summary:
* **Focus:**  Only include information we have explicitly discussed in this session. Do not introduce any new information or topics, even if you have prior knowledge.
* **Accuracy:** Ensure the summary is factually accurate and reflects the nuances of our discussion.
* **Completeness:**  Strive to be as comprehensive and detailed as possible, capturing all key points and insights.
* **Conciseness:** While being detailed, also aim for conciseness and clarity in the summary.
* **Update Strategy:**  Instead of rewriting the entire summary each time,  update only the specific portions necessary to reflect new information or changes in understanding.
"""

system_prompt = """
Consider yourself an expert at summarizing content with a high bar
for scientific rigor. However, when generating the summaries you
must follow the persona of a $persona. This persona will help set
the tone of the conversation. 
"""
